version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "doc/**",
  "**/testsData/**"
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "go"
enabled = true

[[analyzers]]
name = "shell"
enabled = true
  [analyzers.meta]
    dialect = "bash"

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "Dockerfile"
  ]
