---
- id: buildBashBinaries
  name: build bash binaries
  entry: bash-compiler
  language: golang
  pass_filenames: false
  always_run: true
  fail_fast: true
  args:
    - -r
    - .
  stages: [pre-commit]
