binData:
  commands:
    default:
      args:
        - callbacks:
            - argShellcheckFilesCallback
          help: |
            files to validate with shellcheck. If not provided,
            all files from git repository which are beginning
            with a bash shebang, unless --staged option is provided.
          max: -1
          min: 0
          name: shellcheckFiles
          type: StringArray
          variableName: argShellcheckFiles
          functionName: argShellcheckFilesFunction
          authorizedValues:
            - {}
          authorizedValuesList: []
          defaultValue: []
          regexp: ""
      author: "[François Chastanet](https://github.com/fchastanet)"
      callbacks:
        - commandOptionParseFinished
      commandName: shellcheckLint
      copyright: copyrightCallback
      definitionFiles:
        - ${FRAMEWORK_ROOT_DIR}/src/_binaries/commandDefinitions/defaultOptions.sh
        - ${FRAMEWORK_ROOT_DIR}/src/_binaries/commandDefinitions/shellcheckLint.sh
      functionName: shellcheckLintCommand
      help: Lint bash files using shellcheck.
      license: MIT License
      longDescription: |
        shellcheck wrapper that will:
        - install new shellcheck version(${MIN_SHELLCHECK_VERSION}) automatically
        $'\r'
        - by default, lint all git files of this project which are beginning with a bash shebang
          except if the option --staged is passed

        ${__HELP_TITLE}Special configuration .shellcheckrc:${__HELP_NORMAL}
        use the following line in your .shellcheckrc file to exclude
        some files from being checked (use grep -E syntax)
        exclude=^bin/bash-tpl$

        ${__HELP_TITLE_COLOR}SHELLCHECK HELP${__RESET_COLOR}

        @@@SHELLCHECK_HELP@@@
      optionGroups:
        shellcheckLintOptionGroup:
          title: "OPTIONS:"
        default:
          title: Default group
        zzzGroupGlobalOptionsGroup:
          title: "GLOBAL OPTIONS:"
      options:
        - alts:
            - --help
            - -h
          callbacks:
            - optionHelpCallback
          group: zzzGroupGlobalOptionsGroup
          help: Displays this command help
          type: Boolean
          variableName: optionHelp
          functionName: optionHelpFunction
          min: 0
          max: 1
          authorizedValues: []
          authorizedValuesList: []
          regexp: null
          onValue: 1
          offValue: 0
          defaultValue: 0
          helpValueName: null
        - alts:
            - --config
          group: zzzGroupGlobalOptionsGroup
          help: Displays configuration
          type: Boolean
          variableName: optionConfig
          functionName: optionConfigFunction
          min: 0
          max: 1
          callbacks: []
          authorizedValues: []
          authorizedValuesList: []
          regexp: null
          onValue: 1
          offValue: 0
          defaultValue: 0
          helpValueName: null
        - alts:
            - --bash-framework-config
          callbacks:
            - optionBashFrameworkConfigCallback
          group: zzzGroupGlobalOptionsGroup
          help: Use alternate bash framework configuration.
          type: String
          variableName: optionBashFrameworkConfig
          functionName: optionBashFrameworkConfigFunction
          min: 0
          max: 1
          authorizedValues: []
          authorizedValuesList: []
          regexp: ""
          onValue: null
          offValue: null
          defaultValue: ""
          helpValueName: bash-framework-config
        - alts:
            - --verbose
            - -v
          callbacks:
            - optionInfoVerboseCallback
            - updateArgListInfoVerboseCallback
          group: zzzGroupGlobalOptionsGroup
          help: Info level verbose mode (alias of --display-level INFO)
          type: Boolean
          variableName: optionInfoVerbose
          functionName: optionInfoVerboseFunction
          min: 0
          max: 1
          authorizedValues: []
          authorizedValuesList: []
          regexp: null
          onValue: 1
          offValue: 0
          defaultValue: 0
          helpValueName: null
        - alts:
            - -vv
          callbacks:
            - optionDebugVerboseCallback
            - updateArgListDebugVerboseCallback
          group: zzzGroupGlobalOptionsGroup
          help: Debug level verbose mode (alias of --display-level DEBUG)
          type: Boolean
          variableName: optionDebugVerbose
          functionName: optionDebugVerboseFunction
          min: 0
          max: 1
          authorizedValues: []
          authorizedValuesList: []
          regexp: null
          onValue: 1
          offValue: 0
          defaultValue: 0
          helpValueName: null
        - alts:
            - -vvv
          callbacks:
            - optionTraceVerboseCallback
            - updateArgListTraceVerboseCallback
          group: zzzGroupGlobalOptionsGroup
          help: Trace level verbose mode (alias of --display-level TRACE)
          type: Boolean
          variableName: optionTraceVerbose
          functionName: optionTraceVerboseFunction
          min: 0
          max: 1
          authorizedValues: []
          authorizedValuesList: []
          regexp: null
          onValue: 1
          offValue: 0
          defaultValue: 0
          helpValueName: null
        - alts:
            - --env-file
          callbacks:
            - optionEnvFileCallback
            - updateArgListEnvFileCallback
          group: zzzGroupGlobalOptionsGroup
          help:
            Load the specified env file (deprecated, please use
            --bash-framework-config option instead)
          max: -1
          type: StringArray
          variableName: optionEnvFiles
          functionName: optionEnvFilesFunction
          min: 0
          authorizedValues: []
          authorizedValuesList: []
          regexp: ""
          onValue: null
          offValue: null
          defaultValue: []
          helpValueName: env-file
        - alts:
            - --log-level
          authorizedValuesList:
            - "OFF"
            - ERR
            - ERROR
            - WARN
            - WARNING
            - INFO
            - DEBUG
            - TRACE
          callbacks:
            - optionLogLevelCallback
            - updateArgListLogLevelCallback
          group: zzzGroupGlobalOptionsGroup
          help: Set log level
          type: String
          variableName: optionLogLevel
          functionName: optionLogLevelFunction
          min: 0
          max: 1
          authorizedValues:
            - value: "OFF"
              help: "OFF"
            - value: ERR
              help: ERR
            - value: ERROR
              help: ERROR
            - value: WARN
              help: WARN
            - value: WARNING
              help: WARNING
            - value: INFO
              help: INFO
            - value: DEBUG
              help: DEBUG
            - value: TRACE
              help: TRACE
          regexp: ""
          onValue: null
          offValue: null
          defaultValue: ""
          helpValueName: log-level
        - alts:
            - --log-file
          callbacks:
            - optionLogFileCallback
            - updateArgListLogFileCallback
          group: zzzGroupGlobalOptionsGroup
          help: Set log file
          type: String
          variableName: optionLogFile
          functionName: optionLogFileFunction
          min: 0
          max: 1
          authorizedValues: []
          authorizedValuesList: []
          regexp: ""
          onValue: null
          offValue: null
          defaultValue: ""
          helpValueName: log-file
        - alts:
            - --display-level
          authorizedValuesList:
            - "OFF"
            - ERR
            - ERROR
            - WARN
            - WARNING
            - INFO
            - DEBUG
            - TRACE
          callbacks:
            - optionDisplayLevelCallback
            - updateArgListDisplayLevelCallback
          group: zzzGroupGlobalOptionsGroup
          help: Set display level
          type: String
          variableName: optionDisplayLevel
          functionName: optionDisplayLevelFunction
          min: 0
          max: 1
          authorizedValues:
            - value: "OFF"
              help: "OFF"
            - value: ERR
              help: ERR
            - value: ERROR
              help: ERROR
            - value: WARN
              help: WARN
            - value: WARNING
              help: WARNING
            - value: INFO
              help: INFO
            - value: DEBUG
              help: DEBUG
            - value: TRACE
              help: TRACE
          regexp: ""
          onValue: null
          offValue: null
          defaultValue: ""
          helpValueName: display-level
        - alts:
            - --no-color
          callbacks:
            - optionNoColorCallback
            - updateArgListNoColorCallback
          group: zzzGroupGlobalOptionsGroup
          help: Produce monochrome output. alias of --theme noColor.
          type: Boolean
          variableName: optionNoColor
          functionName: optionNoColorFunction
          min: 0
          max: 1
          authorizedValues: []
          authorizedValuesList: []
          regexp: null
          onValue: 1
          offValue: 0
          defaultValue: 0
          helpValueName: null
        - alts:
            - --theme
          authorizedValuesList:
            - default
            - default-force
            - noColor
          callbacks:
            - optionThemeCallback
            - updateArgListThemeCallback
          defaultValue: default
          group: zzzGroupGlobalOptionsGroup
          help:
            Choose color theme - default-force means colors will be produced
            even if command is piped.
          type: String
          variableName: optionTheme
          functionName: optionThemeFunction
          min: 0
          max: 1
          authorizedValues:
            - value: default
              help: default
            - value: default-force
              help: default-force
            - value: noColor
              help: noColor
          regexp: ""
          onValue: null
          offValue: null
          helpValueName: theme
        - alts:
            - --version
          callbacks:
            - optionVersionCallback
          group: zzzGroupGlobalOptionsGroup
          help: Print version information and quit.
          type: Boolean
          variableName: optionVersion
          functionName: optionVersionFunction
          min: 0
          max: 1
          authorizedValues: []
          authorizedValuesList: []
          regexp: null
          onValue: 1
          offValue: 0
          defaultValue: 0
          helpValueName: null
        - alts:
            - --quiet
            - -q
          callbacks:
            - optionQuietCallback
            - updateArgListQuietCallback
          group: zzzGroupGlobalOptionsGroup
          help: Quiet mode, doesn't display any output.
          type: Boolean
          variableName: optionQuiet
          functionName: optionQuietFunction
          min: 0
          max: 1
          authorizedValues: []
          authorizedValuesList: []
          regexp: null
          onValue: 1
          offValue: 0
          defaultValue: 0
          helpValueName: null
        - alts:
            - --format
            - -f
          authorizedValuesList:
            - checkstyle
            - diff
            - gcc
            - json
            - json1
            - quiet
            - tty
          callbacks:
            - test
          defaultValue: tty
          group: shellcheckLintOptionGroup
          help: define output format of this command
          type: String
          variableName: optionFormat
          functionName: optionFormatFunction
          min: 0
          max: 1
          authorizedValues:
            - value: checkstyle
              help: checkstyle
            - value: diff
              help: diff
            - value: gcc
              help: gcc
            - value: json
              help: json
            - value: json1
              help: json1
            - value: quiet
              help: quiet
            - value: tty
              help: tty
          regexp: ""
          onValue: null
          offValue: null
          helpValueName: format
        - alts:
            - --staged
          group: shellcheckLintOptionGroup
          help:
            lint only staged git files(files added to file list to be committed)
            and which are beginning with a bash shebang.
          min: 1
          type: StringArray
          variableName: optionStaged
          functionName: optionStagedFunction
          max: 1
          callbacks: []
          authorizedValues: []
          authorizedValuesList: []
          regexp: ""
          onValue: null
          offValue: null
          defaultValue: []
          helpValueName: staged
        - alts:
            - --xargs
          authorizedValuesList:
            - checkstyle
            - diff
          group: shellcheckLintOptionGroup
          help: uses parallelization(using xargs command) only if tty format
          type: Boolean
          variableName: optionXargs
          functionName: optionXargsFunction
          min: 0
          max: 1
          callbacks: []
          authorizedValues:
            - value: checkstyle
              help: checkstyle
            - value: diff
              help: diff
          regexp: null
          onValue: 1
          offValue: 0
          defaultValue: 0
          helpValueName: null
      sourceFile: ${REPOSITORY_URL}/tree/master/${SRC_FILE_PATH}
      unknownOptionCallbacks:
        - unknownOption
      version: "1.0"
binFile:
  relativeRootDirBasedOnTargetDir: ..
  srcDirs:
    - ${FRAMEWORK_ROOT_DIR}/src
  targetFile: ${FRAMEWORK_ROOT_DIR}/bin/shellcheckLint
  templateDirs:
    - examples/templates
  templateFile: binFile.gtpl
  templateName: binFile
compileConfig:
  BASH_FRAMEWORK_DISPLAY_LEVEL: ${BASH_FRAMEWORK_DISPLAY_LEVEL:-3}
  BASH_FRAMEWORK_LOG_FILE: ${BASH_FRAMEWORK_LOG_FILE:-${FRAMEWORK_ROOT_DIR}/logs/${0##*/}.log}
  BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION: ${BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION:-5}
  BASH_FRAMEWORK_LOG_LEVEL: ${BASH_FRAMEWORK_LOG_LEVEL:-0}
  BASH_FRAMEWORK_THEME: ${BASH_FRAMEWORK_THEME:-default}
  BATS_FILE_NOT_NEEDED_REGEXP:
    - ^bin/
    - .framework-config
    - ^.docker/
    - ^.github/
    - .bats$
    - /testsData/
    - ^manualTests/
    - /_.sh$
    - /ZZZ.sh$
    - /__all.sh$
    - ^src/batsHeaders.sh$
    - ^src/_includes
  COMPILE_PARAMETERS:
    binDir: ${FRAMEWORK_BIN_DIR}
    rootDir: ${FRAMEWORK_ROOT_DIR}
    srcDir: ${FRAMEWORK_SRC_DIR}
    templateDir: ${FRAMEWORK_SRC_DIR}
  DISPLAY_DURATION: ${DISPLAY_DURATION:-1}
  FRAMEWORK_BIN_DIR: ${FRAMEWORK_BIN_DIR:-${FRAMEWORK_ROOT_DIR}/bin}
  FRAMEWORK_FILES_FUNCTION_MATCHING_IGNORE_REGEXP:
    - ^bin/
    - ^.github/
    - ^\.framework-config$
    - \.tpl$
    - /testsData/
    - ^manualTests/
    - \.bats$
    - src/Options/_bats.sh
  FRAMEWORK_FUNCTIONS_IGNORE_REGEXP:
    - Namespace::functions
    - Functions::myFunction
    - Namespace::requireSomething
    - IMPORT::dir::file
    - Acquire::ForceIPv4
  FRAMEWORK_ROOT_DIR: ${FRAMEWORK_ROOT_DIR}
  FRAMEWORK_SRC_DIR: ${FRAMEWORK_SRC_DIR:-${FRAMEWORK_ROOT_DIR}/src}
  FRAMEWORK_SRC_DIRS:
    - ${FRAMEWORK_ROOT_DIR}/src
  FRAMEWORK_VENDOR_BIN_DIR: ${FRAMEWORK_VENDOR_BIN_DIR:-${FRAMEWORK_ROOT_DIR}/vendor/bin}
  FRAMEWORK_VENDOR_DIR: ${FRAMEWORK_VENDOR_DIR:-${FRAMEWORK_ROOT_DIR}/vendor}
  NON_FRAMEWORK_FILES_REGEXP:
    - ^bin/
    - ^hooks/
    - ^test.sh$
    - ^preCommitTest.sh$
    - ^.github/
    - ^.docker/createUser.
    - .framework-config
    - .bats$
    - /testsData/
    - ^manualTests/
    - /_.sh$
    - /ZZZ.sh$
    - /__all.sh$
    - ^src/_binaries
    - ^src/_includes
    - ^src/batsHeaders.sh$
    - ^src/_standalone
vars:
  MAIN_FUNCTION_NAME: main
  REPOSITORY_URL: https://github.com/fchastanet/bash-tools-framework
