@startuml
legend
<u><b>Legend</b></u>
Render Aggregations: true
Render Fields: true
Render Methods: true
Private Aggregations: true
end legend
!include content/assets/classDiagram.puml
namespace compiler {
    class CompileContext << (S,Aquamarine) >> {
        - templateContext render.TemplateContextInterface
        - annotationProcessors []AnnotationProcessorInterface

        - generateCode(compileContextData *CompileContextData, code string) (bool, string, error)
        - functionsAnalysis(compileContextData *CompileContextData, code string) error
        - renderEachFunctionAsTemplate(compileContextData *CompileContextData) error
        - isNonFrameworkFunction(compileContextData *CompileContextData, functionName string) bool
        - nonFrameworkFunctionRegexpCompile(compileContextData *CompileContextData)
        - generateFunctionCode(compileContextData *CompileContextData) (string, error)
        - insertFunctionsCode(compileContextData *CompileContextData, functionNames []string, buffer *bytes.Buffer, insertPosition InsertPosition) error
        - retrieveAllFunctionsContent(compileContextData *CompileContextData) (bool, error)
        - retrieveEachFunctionPath(compileContextData *CompileContextData) (bool, error)
        - extractUniqueFrameworkFunctions(compileContextData *CompileContextData, code string) bool
        - findFileInSrcDirs(compileContextData *CompileContextData, relativeFilePath string) (string, bool)

    }
    class CompileContextData << (S,Aquamarine) >> {
        - compileContext *CompileContext
        - templateContextData *render.TemplateContextData
        - config *model.CompilerConfig
        - functionsMap <font color=blue>map</font>[string]functionInfoStruct
        - ignoreFunctionsRegexp []*regexp.Regexp

    }
    class annotationEmbedGenerate << (S,Aquamarine) >> {
        - embedDirTemplateName string
        - embedFileTemplateName string
        - templateContextData *render.TemplateContextData

        - renderFile(asName string, resource string, fileMode os.FileMode) (string, error)
        - renderDir(asName string, resource string) (string, error)
        - renderTemplate(data <font color=blue>map</font>[string]string, templateName string) (string, error)

    }
    class duplicatedAsNameError << (S,Aquamarine) >> {
        - lineNumber int
        - asName string
        - resource string

    }
    class embedAnnotationProcessor << (S,Aquamarine) >> {
        - annotationEmbedGenerate annotationEmbedGenerateInterface
        - embedMap <font color=blue>map</font>[string]string

    }
    class functionInfoStruct << (S,Aquamarine) >> {
        - getRequireAnnotation() (*requireAnnotation, error)

    }
    class requireAnnotation << (S,Aquamarine) >> {
        - requiredFunctions []string
        - isRequired bool
        - checkRequirementsCodeAdded bool
        - codeAddedOnRequiredFunctions bool

    }
    class requireAnnotationProcessor << (S,Aquamarine) >> {
        - compileContextData *CompileContextData
        - checkRequirementsTemplateName string
        - requireTemplateName string

        - addRequireCodeToEachRequiredFunctions(compileContextData *CompileContextData, functionStruct *functionInfoStruct) error
        - addRequireCode(compileContextData *CompileContextData, functionStruct *functionInfoStruct) error

    }
    class requiredFunctionNotFoundError << (S,Aquamarine) >> {
        - functionName string

    }
    class unsupportedEmbeddedResourceError << (S,Aquamarine) >> {
        - asName string
        - resource string
        - lineNumber int

    }
}
namespace model {
    class BinaryModelLoader << (S,Aquamarine) >> {
        - setEnvVars(binaryModel *BinaryModel)
        - expandVars(binaryModel *BinaryModel)

    }
}
namespace services {
    class BinaryModelServiceContext << (S,Aquamarine) >> {
        - binaryModelLoader BinaryModelLoaderInterface
        - templateContext TemplateContextInterface
        - codeCompiler CodeCompilerInterface

        - renderBinaryCodeFromTemplate(binaryModelServiceContextData *BinaryModelServiceContextData) (string, error)
        - renderCode(binaryModelServiceContextData *BinaryModelServiceContextData) (string, error)

    }
    class BinaryModelServiceContextData << (S,Aquamarine) >> {
        - binaryModelData *model.BinaryModel
        - compileContextData *compiler.CompileContextData
        - templateContextData *render.TemplateContextData
        - targetDir string
        - keepIntermediateFiles bool
        - binaryModelFilePath string
        - binaryModelBaseName string

    }
}
"__builtin__.[]string" #.. "alias of""main.YamlFiles"
"__builtin__.int8" #.. "alias of""compiler.InsertPosition"
"__builtin__.string" #.. "alias of""main.Directory"
"__builtin__.string" #.. "alias of""main.VersionFlag"
"structures.<font color=blue>map</font>[string]<font color=blue>interface</font>{}" #.. "alias of""structures.Dictionary"
@enduml
