compilerConfig:
  binDir: ${BASH_DEV_ENV_ROOT_DIR}/bin
  rootDir: root
  targetFile: target
  templateFile: template
  annotationsConfig:
    requireTemplateName: requireTemplateName
    checkRequirementsTemplateName: checkRequirementsTemplateName
    embedFileTemplateName: invalidé
binData:
  commands:
    default:
      commandName: command
