@startuml

'!pragma layout elk

package main {
  [Main] ..> ParseCliInterface
  [Main] ..> BinaryModelServiceInterface
  ParseCliInterface )-- [ParseCli]  : <<implements>>
}

package services {
  BinaryModelServiceInterface )-- [BinaryModelService] : <<implements>>
  [BinaryModelService] ..> BinaryModelInterface : <<uses>>
  [BinaryModelService] ..> TemplateContextInterface : <<uses>>
  [BinaryModelService] ..> CodeGeneratorInterface : <<uses>>
  [BinaryModelService] ..> CompilerInterface : <<uses>>
}

package model {
  BinaryModelInterface )-- [BinaryModel] : <<implements>>
}

package render {
  TemplateContextInterface )-- [TemplateContext] : <<implements>>
}

package generator {
  CodeGeneratorInterface )-- [CodeGenerator] : <<implements>>
  [CodeGenerator] ..> TemplateRenderingInterface
  TemplateRenderingInterface )-- [TemplateContext] : <<implements>>
}

package compiler {
  CompilerInterface )-- [Compiler] : <<implements>>
}

@enduml
