---
compileConfig:
  FRAMEWORK_ROOT_DIR: ${FRAMEWORK_ROOT_DIR}
  FRAMEWORK_SRC_DIR: ${FRAMEWORK_SRC_DIR:-${FRAMEWORK_ROOT_DIR}/src}
  FRAMEWORK_BIN_DIR: ${FRAMEWORK_BIN_DIR:-${FRAMEWORK_ROOT_DIR}/bin}
  FRAMEWORK_VENDOR_DIR: ${FRAMEWORK_VENDOR_DIR:-${FRAMEWORK_ROOT_DIR}/vendor}
  FRAMEWORK_VENDOR_BIN_DIR: ${FRAMEWORK_VENDOR_BIN_DIR:-${FRAMEWORK_ROOT_DIR}/vendor/bin}

  # compile parameters
  # srcFile     : file that needs to be compiled
  # templateDir : directory from which bash-tpl templates will be searched
  # binDir      : fallback bin directory in case BIN_FILE has not been provided
  # rootDir     : directory used to compute src file relative path
  # srcDirs     : additional directories where to find the functions
  COMPILE_PARAMETERS:
    srcDir: ${FRAMEWORK_SRC_DIR}
    binDir: ${FRAMEWORK_BIN_DIR}
    rootDir: ${FRAMEWORK_ROOT_DIR}
    templateDir: ${FRAMEWORK_SRC_DIR}

  # describe the functions that will be skipped from being imported
  FRAMEWORK_FUNCTIONS_IGNORE_REGEXP:
    - Namespace::functions
    - Functions::myFunction
    - Namespace::requireSomething
    - IMPORT::dir::file
    - Acquire::ForceIPv4

  # describe the files that do not contain function to be imported
  NON_FRAMEWORK_FILES_REGEXP:
    - ^bin/
    - ^hooks/
    - ^test.sh$
    - ^preCommitTest.sh$
    - ^.github/
    - ^.docker/createUser.
    - .framework-config
    - .bats$
    - /testsData/
    - ^manualTests/
    - /_.sh$
    - /ZZZ.sh$
    - /__all.sh$
    - ^src/_binaries
    - ^src/_includes
    - ^src/batsHeaders.sh$
    - ^src/_standalone

  # describe the files that are allowed to not have an associated bats file
  BATS_FILE_NOT_NEEDED_REGEXP:
    - ^bin/
    - .framework-config
    - ^.docker/
    - ^.github/
    - .bats$
    - /testsData/
    - ^manualTests/
    - /_.sh$
    - /ZZZ.sh$
    - /__all.sh$
    - ^src/batsHeaders.sh$
    - ^src/_includes

  # describe the files that are allowed to not have a function matching the filename
  FRAMEWORK_FILES_FUNCTION_MATCHING_IGNORE_REGEXP:
    - ^bin/
    - ^.github/
    - ^\.framework-config$
    - \.tpl$
    - /testsData/
    - ^manualTests/
    - \.bats$
    - src/Options/_bats.sh

  # Source directories
  FRAMEWORK_SRC_DIRS:
    - "${FRAMEWORK_ROOT_DIR}/src"

  BASH_FRAMEWORK_THEME: ${BASH_FRAMEWORK_THEME:-default}
  BASH_FRAMEWORK_LOG_LEVEL: ${BASH_FRAMEWORK_LOG_LEVEL:-0}
  BASH_FRAMEWORK_DISPLAY_LEVEL: ${BASH_FRAMEWORK_DISPLAY_LEVEL:-3}
  BASH_FRAMEWORK_LOG_FILE: ${BASH_FRAMEWORK_LOG_FILE:-${FRAMEWORK_ROOT_DIR}/logs/${0##*/}.log}
  BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION: ${BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION:-5}

  # display elapsed time since last log
  DISPLAY_DURATION: ${DISPLAY_DURATION:-1}
