---
compilerConfig: &defaultFrameworkConfig
  # compile parameters
  # rootDir     : directory used to compute src file relative path
  # srcDirs     : additional directories where to find the functions
  # templateDir : directory from which bash-tpl templates will be searched
  # binDir      : fallback bin directory in case BIN_FILE has not been provided
  rootDir: ${FRAMEWORK_ROOT_DIR}
  srcDirs:
    - ${FRAMEWORK_ROOT_DIR}/src
  binDir: ${FRAMEWORK_ROOT_DIR}/bin
  templateDir: ${FRAMEWORK_SRC_DIR}
  vendorDir: ${FRAMEWORK_VENDOR_DIR:-${FRAMEWORK_ROOT_DIR}/vendor}
  vendorBinDir: ${FRAMEWORK_VENDOR_BIN_DIR:-${FRAMEWORK_ROOT_DIR}/vendor/bin}

  # describe the functions that will be skipped from being imported
  functionsIgnoreRegexpList:
    - Namespace::functions
    - Functions::myFunction
    - Namespace::requireSomething
    - IMPORT::dir::file
    - Acquire::ForceIPv4
