compilerConfig:
  binDir: ${BASH_DEV_ENV_ROOT_DIR}/bin
  rootDir: root
  targetFile: target
  templateFile: template
  annotationsConfig:
    checkRequirementsTemplateName:
    embedDirTemplateName:
    embedFileTemplateName:
    requireTemplateName:
binData:
  commands:
    default:
      commandName: command
