binData:
  commands:
    default:
      afterParseCallbacks: []
      args: []
      author: ""
      beforeParseCallbacks: []
      callbacks: []
      commandName: command
      copyright: ""
      copyrightBeginYear: ""
      everyArgumentCallbacks: []
      functionName: commandFunction
      help: ""
      license: ""
      longDescription: ""
      options: []
      sourceFile: ""
      unknownArgumentCallbacks: []
      unknownOptionCallbacks: []
      version: 1.0.0
compilerConfig:
  annotationsConfig:
    checkRequirementsTemplateName: checkRequirements
    embedDirTemplateName: embedDir
    embedFileTemplateName: embedFile
    requireTemplateName: require
  binDir: rootDir/bin
  functionsIgnoreRegexpList: []
  relativeRootDirBasedOnTargetDir: .
  rootDir: rootDir
  srcDirs:
  - rootDir/src
  targetFile: targetFile
  templateDirs:
  - rootDir/template
  templateFile: templateFile
